apiVersion: v1
kind: Service
metadata:
  name: lottery-service
  labels:
    app: lottery-service
    service: lottery-service
spec:
  ports:
    - port: 9090
      name: http
  selector:
    app: lottery-service
    
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: lottery-service
  labels:
    account: lottery-service
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: lottery-service-v1
  labels:
    app: lottery-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lottery-service
      version: v1
  template:
    metadata:
      labels:
        app: lottery-service
        version: v1
    spec:
      serviceAccountName: lottery-service
      containers:
        - name: lottery-service
          image: hpreethip/lottery-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          securityContext:
            runAsUser: 1000